version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./code:/code
